spring:
    application:
        name: filter-service
    cloud:
        config:
            profile: ${PROFILE}
    config:
        import: configserver:http://localhost:9004,optional:file:.env[.properties]